name: bookflix_demo
description: "BookFlix - Registra y lleva control de tus libros leídos y películas vistas"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.0

  # Authentication & Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  local_auth: ^2.3.0

  # State Management & Navigation
  provider: ^6.1.2
  go_router: ^14.3.0

  # Storage & Data
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # Media Players (video/pdf/file support)
  video_player: ^2.9.2
  chewie: ^1.8.5
  flutter_pdfview: ^1.3.2
  file_picker: ^8.1.2

  # Notifications
  flutter_local_notifications: ^17.2.3
  awesome_notifications: ^0.9.3+1

  # Network & API
  http: ^1.2.2
  dio: ^5.7.0

  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  lottie: ^3.1.2
  flutter_rating_bar: ^4.0.1

  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/sample_books/
    - assets/sample_movies/

  # Fonts (opcional: descomentar si usas tipografía custom)
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
